mutation AddEmployee($create: EmployeeInput!) {
  addEmployee(create: $create) {
    ...EmployeeDetails
  }
}

mutation UpdateEmployee($update: EmployeeUpdateInput!) {
  updateEmployee(update: $update) {
    ...EmployeeDetails
  }
}

mutation DeleteEmployee($delete: EmployeeDeleteInput!) {
  deleteEmployee(delete: $delete) {
    ...EmployeeDetails
  }
}
